/***************************************************************************
* Copyright (c) 2017, Nico Caprioli                                        *
*                                                                          *
* Distributed under the terms of the LGPLv3 License.                       *
*                                                                          *
* The full license is in the file LICENSE, distributed with this software. *
****************************************************************************/
#pragma once
#include <memory>
#include <string_view>
#include <unordered_map>
#include "NumericLiterals.hpp"
#include "aria/roles/AriaRole.hpp"

namespace WebBinaryCompression::Aria::Values::Roles {
using namespace std::string_view_literals;
/**
 * \brief Maps all \link Aria::AriaRole \endlink names to their equivalent.
 */
const std::unordered_map<std::string_view, std::shared_ptr<AriaRole>,
                         AriaRoleHasher> elements = {
  {
    "alert"sv,
    std::make_shared<AriaRole>(0x06_uint8)
  },
  {
    "alertdialog"sv,
    std::make_shared<AriaRole>(0x07_uint8)
  },
  {
    "application"sv,
    std::make_shared<AriaRole>(0x08_uint8)
  },
  {
    "article"sv,
    std::make_shared<AriaRole>(0x09_uint8)
  },
  {
    "banner"sv,
    std::make_shared<AriaRole>(0x0A_uint8)
  },
  {
    "button"sv,
    std::make_shared<AriaRole>(0x0B_uint8)
  },
  {
    "cell"sv,
    std::make_shared<AriaRole>(0x0C_uint8)
  },
  {
    "checkbox"sv,
    std::make_shared<AriaRole>(0x0D_uint8)
  },
  {
    "columnheader"sv,
    std::make_shared<AriaRole>(0x0E_uint8)
  },
  {
    "combobox"sv,
    std::make_shared<AriaRole>(0x0F_uint8)
  },
  {
    "complementary"sv,
    std::make_shared<AriaRole>(0x10_uint8)
  },
  {
    "contentinfo"sv,
    std::make_shared<AriaRole>(0x11_uint8)
  },
  {
    "definition"sv,
    std::make_shared<AriaRole>(0x12_uint8)
  },
  {
    "dialog"sv,
    std::make_shared<AriaRole>(0x13_uint8)
  },
  {
    "directory"sv,
    std::make_shared<AriaRole>(0x14_uint8)
  },
  {
    "document"sv,
    std::make_shared<AriaRole>(0x15_uint8)
  },
  {
    "feed"sv,
    std::make_shared<AriaRole>(0x16_uint8)
  },
  {
    "figure"sv,
    std::make_shared<AriaRole>(0x17_uint8)
  },
  {
    "form"sv,
    std::make_shared<AriaRole>(0x18_uint8)
  },
  {
    "grid"sv,
    std::make_shared<AriaRole>(0x19_uint8)
  },
  {
    "gridcell"sv,
    std::make_shared<AriaRole>(0x1A_uint8)
  },
  {
    "group"sv,
    std::make_shared<AriaRole>(0x1B_uint8)
  },
  {
    "heading"sv,
    std::make_shared<AriaRole>(0x1C_uint8)
  },
  {
    "img"sv,
    std::make_shared<AriaRole>(0x1D_uint8)
  },
  {
    "link"sv,
    std::make_shared<AriaRole>(0x1E_uint8)
  },
  {
    "list"sv,
    std::make_shared<AriaRole>(0x1F_uint8)
  },
  {
    "listbox"sv,
    std::make_shared<AriaRole>(0x20_uint8)
  },
  {
    "listitem"sv,
    std::make_shared<AriaRole>(0x21_uint8)
  },
  {
    "log"sv,
    std::make_shared<AriaRole>(0x22_uint8)
  },
  {
    "main"sv,
    std::make_shared<AriaRole>(0x23_uint8)
  },
  {
    "marquee"sv,
    std::make_shared<AriaRole>(0x24_uint8)
  },
  {
    "math"sv,
    std::make_shared<AriaRole>(0x25_uint8)
  },
  {
    "menu"sv,
    std::make_shared<AriaRole>(0x26_uint8)
  },
  {
    "menubar"sv,
    std::make_shared<AriaRole>(0x27_uint8)
  },
  {
    "menuitem"sv,
    std::make_shared<AriaRole>(0x28_uint8)
  },
  {
    "menuitemcheckbox"sv,
    std::make_shared<AriaRole>(0x29_uint8)
  },
  {
    "menuitemradio"sv,
    std::make_shared<AriaRole>(0x2A_uint8)
  },
  {
    "navigation"sv,
    std::make_shared<AriaRole>(0x2B_uint8)
  },
  {
    "none"sv,
    std::make_shared<AriaRole>(0x2C_uint8)
  },
  {
    "note"sv,
    std::make_shared<AriaRole>(0x2D_uint8)
  },
  {
    "option"sv,
    std::make_shared<AriaRole>(0x2E_uint8)
  },
  {
    "presentation"sv,
    std::make_shared<AriaRole>(0x2F_uint8)
  },
  {
    "progressbar"sv,
    std::make_shared<AriaRole>(0x30_uint8)
  },
  {
    "radio"sv,
    std::make_shared<AriaRole>(0x31_uint8)
  },
  {
    "radiogroup"sv,
    std::make_shared<AriaRole>(0x32_uint8)
  },
  {
    "region"sv,
    std::make_shared<AriaRole>(0x33_uint8)
  },
  {
    "row"sv,
    std::make_shared<AriaRole>(0x34_uint8)
  },
  {
    "rowgroup"sv,
    std::make_shared<AriaRole>(0x35_uint8)
  },
  {
    "rowheader"sv,
    std::make_shared<AriaRole>(0x36_uint8)
  },
  {
    "scrollbar"sv,
    std::make_shared<AriaRole>(0x37_uint8)
  },
  {
    "search"sv,
    std::make_shared<AriaRole>(0x38_uint8)
  },
  {
    "searchbox"sv,
    std::make_shared<AriaRole>(0x39_uint8)
  },
  {
    "separator"sv,
    std::make_shared<AriaRole>(0x3A_uint8)
  },
  {
    "slider"sv,
    std::make_shared<AriaRole>(0x3B_uint8)
  },
  {
    "spinbutton"sv,
    std::make_shared<AriaRole>(0x3C_uint8)
  },
  {
    "status"sv,
    std::make_shared<AriaRole>(0x3D_uint8)
  },
  {
    "switch"sv,
    std::make_shared<AriaRole>(0x3E_uint8)
  },
  {
    "tab"sv,
    std::make_shared<AriaRole>(0x3F_uint8)
  },
  {
    "table"sv,
    std::make_shared<AriaRole>(0x40_uint8)
  },
  {
    "tablist"sv,
    std::make_shared<AriaRole>(0x41_uint8)
  },
  {
    "tabpanel"sv,
    std::make_shared<AriaRole>(0x42_uint8)
  },
  {
    "term"sv,
    std::make_shared<AriaRole>(0x43_uint8)
  },
  {
    "textbox"sv,
    std::make_shared<AriaRole>(0x44_uint8)
  },
  {
    "timer"sv,
    std::make_shared<AriaRole>(0x45_uint8)
  },
  {
    "toolbar"sv,
    std::make_shared<AriaRole>(0x46_uint8)
  },
  {
    "tooltip"sv,
    std::make_shared<AriaRole>(0x47_uint8)
  },
  {
    "tree"sv,
    std::make_shared<AriaRole>(0x48_uint8)
  },
  {
    "treegrid"sv,
    std::make_shared<AriaRole>(0x49_uint8)
  },
  {
    "treeitem"sv,
    std::make_shared<AriaRole>(0x4A_uint8)
  }
};
}  // namespace WebBinaryCompression::Aria::Values::Roles
